// Vocabulary and sentences from the Thai Practice Workbook.
// Keep each entry on one line: tools/generate_audio.py reads this file line by line.
//
// Words: `en` lists accepted English answers, the first is shown as the meaning.
// `hint` disambiguates the English prompt when two Thai words share a meaning.
const VOCAB = [
  { id: 'v-chop', thai: 'ชอบ', rom: 'chôrp', en: ['like', 'to like'] },
  { id: 'v-kin', thai: 'กิน', rom: 'gin', en: ['eat', 'to eat'] },
  { id: 'v-duem', thai: 'ดื่ม', rom: 'dùum', en: ['drink', 'to drink'] },
  { id: 'v-arai', thai: 'อะไร', rom: 'à-rai', en: ['what'] },
  { id: 'v-somtam', thai: 'ส้มตำ', rom: 'sôm tam', en: ['papaya salad', 'som tam', 'somtam', 'green papaya salad'] },
  { id: 'v-cha', thai: 'ชา', rom: 'chaa', en: ['tea'] },
  { id: 'v-kafae', thai: 'กาแฟ', rom: 'gaa-fae', en: ['coffee'] },
  { id: 'v-khao', thai: 'ข้าว', rom: 'khâao', en: ['rice', 'food', 'meal', 'cooked rice'] },
  { id: 'v-phet', thai: 'เผ็ด', rom: 'phèt', en: ['spicy', 'hot'] },
  { id: 'v-pai', thai: 'ไป', rom: 'bpai', en: ['go', 'to go'] },
  { id: 'v-ma', thai: 'มา', rom: 'maa', en: ['come', 'to come'] },
  { id: 'v-nai', thai: 'ไหน', rom: 'nǎi', en: ['where', 'which'], hint: 'not the question particle' },
  { id: 'v-rankafae', thai: 'ร้านกาแฟ', rom: 'ráan gaa-fae', en: ['coffee shop', 'cafe', 'café', 'coffee house'] },
  { id: 'v-supermarket', thai: 'ซูเปอร์มาร์เก็ต', rom: 'suu-bpəə-maa-gèt', en: ['supermarket'] },
  { id: 'v-talat', thai: 'ตลาด', rom: 'dtà-làat', en: ['market'] },
  { id: 'v-ban', thai: 'บ้าน', rom: 'bâan', en: ['house', 'home'] },
  { id: 'v-rongrian', thai: 'โรงเรียน', rom: 'roong-rian', en: ['school'] },
  { id: 'v-thamngan', thai: 'ทำงาน', rom: 'tham-ngaan', en: ['work', 'to work'] },
  { id: 'v-pen', thai: 'เป็น', rom: 'bpen', en: ['to be', 'be', 'am', 'is', 'are', 'am is are'] },
  { id: 'v-khon', thai: 'คน', rom: 'khon', en: ['person', 'people'] },
  { id: 'v-canada', thai: 'แคนาดา', rom: 'khae-naa-daa', en: ['Canada'] },
  { id: 'v-thailand', thai: 'ประเทศไทย', rom: 'bprà-thêet thai', en: ['Thailand'] },
  { id: 'v-khoei', thai: 'เคย', rom: 'kəəi', en: ['ever', 'used to', 'have ever', 'have been', 'ever done'], hint: 'past experience' },
  { id: 'v-ja', thai: 'จะ', rom: 'jà', en: ['will', 'going to', 'shall', 'future'] },
  { id: 'v-yang', thai: 'ยัง', rom: 'yang', en: ['yet', 'still', 'not yet'] },
  { id: 'v-laeo', thai: 'แล้ว', rom: 'láew', en: ['already'] },
  { id: 'v-maidai', thai: 'ไม่ได้', rom: 'mâi dâai', en: ['did not', 'didnt', 'have not', 'havent', 'not', 'cannot', 'cant'], hint: 'past negative' },
  { id: 'v-mai-neg', thai: 'ไม่', rom: 'mâi', en: ['not', 'no', 'dont', 'do not'], hint: 'plain negative' },
  { id: 'v-mai-q', thai: 'ไหม', rom: 'mǎi', en: ['question particle', 'question', 'yes no question', 'question word', '?'], hint: 'yes/no question particle' },
  { id: 'v-khao-pron', thai: 'เขา', rom: 'khǎo', en: ['he', 'she', 'they', 'him', 'her', 'them', 'he she', 'he she they'] },
  { id: 'v-rao', thai: 'เรา', rom: 'rao', en: ['we', 'us'] },
  { id: 'v-chan', thai: 'ฉัน', rom: 'chǎn', en: ['I', 'me'] },
  { id: 'v-khun', thai: 'คุณ', rom: 'khun', en: ['you'] },
  { id: 'v-mani', thai: 'มานี่', rom: 'maa nîi', en: ['come here'] },
  { id: 'v-khopkhun', thai: 'ขอบคุณ', rom: 'khàawp-khun', en: ['thank you', 'thanks'] },
  { id: 'v-mak', thai: 'มาก', rom: 'mâak', en: ['very', 'a lot', 'much', 'very much', 'lots', 'many'] },
  { id: 'v-maipenrai', thai: 'ไม่เป็นไร', rom: 'mâi bpen rai', en: ['never mind', 'no problem', 'youre welcome', 'no worries', 'its ok', 'its okay', 'thats ok', 'thats okay', 'it is ok'] },
  { id: 'v-khrap', thai: 'ครับ', rom: 'khráp', en: ['polite particle', 'polite', 'male polite particle', 'politeness particle', 'polite word'], hint: 'used by men' },
  { id: 'v-tae', thai: 'แต่', rom: 'dtàae', en: ['but'] },

  // Numbers 1–10. Thai digits (๑–๑๐) are accepted too.
  { id: 'v-num-1', thai: 'หนึ่ง', rom: 'nʉ̀ng', en: ['one', '1'], thAlt: ['๑'] },
  { id: 'v-num-2', thai: 'สอง', rom: 'sǒrng', en: ['two', '2'], thAlt: ['๒'] },
  { id: 'v-num-3', thai: 'สาม', rom: 'sǎam', en: ['three', '3'], thAlt: ['๓'] },
  { id: 'v-num-4', thai: 'สี่', rom: 'sìi', en: ['four', '4'], thAlt: ['๔'] },
  { id: 'v-num-5', thai: 'ห้า', rom: 'hâa', en: ['five', '5'], thAlt: ['๕'] },
  { id: 'v-num-6', thai: 'หก', rom: 'hòk', en: ['six', '6'], thAlt: ['๖'] },
  { id: 'v-num-7', thai: 'เจ็ด', rom: 'jèt', en: ['seven', '7'], thAlt: ['๗'] },
  { id: 'v-num-8', thai: 'แปด', rom: 'bpàaet', en: ['eight', '8'], thAlt: ['๘'] },
  { id: 'v-num-9', thai: 'เก้า', rom: 'gâo', en: ['nine', '9'], thAlt: ['๙'] },
  { id: 'v-num-10', thai: 'สิบ', rom: 'sìp', en: ['ten', '10'], thAlt: ['๑๐'] },

  // Everyday verbs and words from a video lesson.
  { id: 'v-yu', thai: 'อยู่', rom: 'yùu', en: ['stay', 'to stay', 'be at', 'to be at', 'live', 'to live'], hint: 'be somewhere' },
  { id: 'v-phuean', thai: 'เพื่อน', rom: 'phʉ̂an', en: ['friend', 'friends'] },
  { id: 'v-thi', thai: 'ที่', rom: 'thîi', en: ['at', 'place', 'at the'], hint: 'location word' },
  { id: 'v-non', thai: 'นอน', rom: 'norn', en: ['sleep', 'to sleep', 'go to bed', 'lie down'] },
  { id: 'v-wanni', thai: 'วันนี้', rom: 'wan-níi', en: ['today'] },
  { id: 'v-duek', thai: 'ดึก', rom: 'dʉ̀k', en: ['late at night', 'late', 'late night'] },
  { id: 'v-mueakhuen', thai: 'เมื่อคืน', rom: 'mʉ̂a-khʉʉn', en: ['last night'] },
  { id: 'v-tuen', thai: 'ตื่น', rom: 'dtʉ̀ʉn', en: ['wake up', 'to wake up', 'wake', 'get up'] },
  { id: 'v-chao', thai: 'เช้า', rom: 'cháao', en: ['morning', 'early', 'early morning', 'in the morning'] },
  { id: 'v-thuk', thai: 'ทุก', rom: 'thúk', en: ['every', 'each', 'all'] },
  { id: 'v-wan', thai: 'วัน', rom: 'wan', en: ['day'] },
  { id: 'v-phut', thai: 'พูด', rom: 'phûut', en: ['speak', 'to speak', 'talk', 'to talk', 'say'] },
  { id: 'v-thai', thai: 'ไทย', rom: 'thai', en: ['Thai'] },
  { id: 'v-nitnoi', thai: 'นิดหน่อย', rom: 'nít-nàwy', en: ['a little', 'a bit', 'a little bit', 'little'], hint: 'a small amount' },
  { id: 'v-yak', thai: 'อยาก', rom: 'yàak', en: ['want', 'want to', 'to want', 'would like'] },
  { id: 'v-noi', thai: 'น้อย', rom: 'nóoi', en: ['little', 'less', 'few', 'not much'], hint: 'opposite of มาก' },
  { id: 'v-tho', thai: 'โทร', rom: 'thoo', en: ['call', 'to call', 'phone', 'to phone', 'telephone'] },
  { id: 'v-ha', thai: 'หา', rom: 'hǎa', en: ['look for', 'to look for', 'find', 'seek', 'visit'] },
  { id: 'v-sue', thai: 'ซื้อ', rom: 'sʉ́ʉ', en: ['buy', 'to buy', 'purchase'] },
  { id: 'v-du', thai: 'ดู', rom: 'duu', en: ['watch', 'to watch', 'see', 'look', 'look at', 'to see'] },
  { id: 'v-nang', thai: 'หนัง', rom: 'nǎng', en: ['movie', 'film', 'movies'] },
  { id: 'v-tham', thai: 'ทำ', rom: 'tham', en: ['do', 'to do', 'make', 'to make'] },
  { id: 'v-an', thai: 'อ่าน', rom: 'àan', en: ['read', 'to read'] },
  { id: 'v-nangsue', thai: 'หนังสือ', rom: 'nǎng-sʉ̌ʉ', en: ['book', 'books'] },
  { id: 'v-khian', thai: 'เขียน', rom: 'khǐan', en: ['write', 'to write'] },
  { id: 'v-phasa', thai: 'ภาษา', rom: 'phaa-sǎa', en: ['language'] },
];

// Words that appear inside sentences but aren't vocabulary cards.
const EXTRA_GLOSS = {
  'หรือ': { rom: 'rʉ̌ʉ', en: 'or (หรือยัง = "…yet?")' },
  'นี่': { rom: 'nîi', en: 'here / this' },
  'ไม่เป็น': { rom: 'mâi bpen', en: "can't (don't know how)" },
};

// Sentences: `words` splits the Thai into vocabulary chunks (word bank + gloss hints).
// `en` = accepted English (first is the model answer); `key` = every group must appear
// for a looser answer to count; `avoid` = words that mean it was misread (ไหม ≠ ไหน);
// `thAlt` = other acceptable Thai.
const SENTENCES = [
  { id: 's-01', thai: 'คุณชอบกินอะไร', rom: 'khun chôrp gin à-rai', words: ['คุณ', 'ชอบ', 'กิน', 'อะไร'], en: ['What do you like to eat?', 'What do you like eating?'], key: [['what'], ['like'], ['eat', 'eating']] },
  { id: 's-02', thai: 'ฉันชอบกินส้มตำ', rom: 'chǎn chôrp gin sôm tam', words: ['ฉัน', 'ชอบ', 'กิน', 'ส้มตำ'], en: ['I like to eat papaya salad.', 'I like eating papaya salad.', 'I like to eat som tam.', 'I like eating som tam.'], key: [['i'], ['like'], ['papaya salad', 'som tam', 'somtam']] },
  { id: 's-03', thai: 'คุณไปไหนมา', rom: 'khun bpai nǎi maa', words: ['คุณ', 'ไป', 'ไหน', 'มา'], en: ['Where have you been?', 'Where did you go?'], key: [['where'], ['been', 'go', 'went']] },
  { id: 's-04', thai: 'ฉันไปร้านกาแฟมา', rom: 'chǎn bpai ráan gaa-fae maa', words: ['ฉัน', 'ไป', 'ร้านกาแฟ', 'มา'], en: ['I went to the coffee shop.', 'I have been to the coffee shop.', 'I went to the cafe.', 'I have been to the cafe.'], key: [['i'], ['went', 'been', 'go'], ['coffee shop', 'cafe', 'café', 'coffee']] },
  { id: 's-05', thai: 'คุณเป็นคนอะไร', rom: 'khun bpen khon à-rai', words: ['คุณ', 'เป็น', 'คน', 'อะไร'], en: ['What nationality are you?', 'Where are you from?'], key: [['nationality', 'where are you from', 'where you from']] },
  { id: 's-06', thai: 'ฉันเป็นคนแคนาดา', rom: 'chǎn bpen khon khae-naa-daa', words: ['ฉัน', 'เป็น', 'คน', 'แคนาดา'], en: ['I am Canadian.', 'I am a Canadian.', 'I am from Canada.'], key: [['i'], ['canadian', 'canada']] },
  { id: 's-07', thai: 'คุณกินข้าวหรือยัง', rom: 'khun gin khâao rʉ̌ʉ yang', words: ['คุณ', 'กิน', 'ข้าว', 'หรือ', 'ยัง'], en: ['Have you eaten yet?', 'Have you eaten?', 'Did you eat yet?'], key: [['you'], ['eat', 'eaten', 'ate'], ['yet', 'have', 'did']], thAlt: ['กินข้าวหรือยัง', 'กินข้าวยัง', 'คุณกินข้าวยัง'] },
  { id: 's-08', thai: 'ฉันกินข้าวแล้ว', rom: 'chǎn gin khâao láew', words: ['ฉัน', 'กิน', 'ข้าว', 'แล้ว'], en: ['I have already eaten.', 'I already ate.', 'I ate already.', 'I have eaten.'], key: [['i'], ['eaten', 'ate', 'eat'], ['already', 'have eaten']], thAlt: ['กินข้าวแล้ว'] },
  { id: 's-09', thai: 'คุณเคยไปประเทศไทยไหม', rom: 'khun kəəi bpai bprà-thêet thai mǎi', words: ['คุณ', 'เคย', 'ไป', 'ประเทศไทย', 'ไหม'], en: ['Have you ever been to Thailand?', 'Have you been to Thailand?'], key: [['you'], ['been', 'gone', 'go', 'went'], ['thailand']], avoid: ['which', 'where'] },
  { id: 's-10', thai: 'ฉันเคยไป', rom: 'chǎn kəəi bpai', words: ['ฉัน', 'เคย', 'ไป'], en: ['I have been.', 'I have been before.', 'I have been there.', 'I have gone before.'], key: [['i'], ['have been', 'have gone', 'been before', 'went before', 'been there']] },
  { id: 's-11', thai: 'คุณจะไปทำงานไหม', rom: 'khun jà bpai tham-ngaan mǎi', words: ['คุณ', 'จะ', 'ไป', 'ทำงาน', 'ไหม'], en: ['Are you going to work?', 'Will you go to work?'], key: [['you'], ['going', 'will'], ['work']], avoid: ['which', 'where'] },
  { id: 's-12', thai: 'ฉันจะไปทำงาน', rom: 'chǎn jà bpai tham-ngaan', words: ['ฉัน', 'จะ', 'ไป', 'ทำงาน'], en: ['I will go to work.', 'I am going to work.', 'I am going to go to work.'], key: [['i'], ['will', 'going'], ['work']] },
  { id: 's-13', thai: 'เขาไม่ชอบกินเผ็ด', rom: 'khǎo mâi chôrp gin phèt', words: ['เขา', 'ไม่', 'ชอบ', 'กิน', 'เผ็ด'], en: ['He does not like spicy food.', 'He does not like eating spicy food.', 'She does not like spicy food.', 'They do not like spicy food.'], key: [['he', 'she', 'they'], ['not'], ['like'], ['spicy', 'hot']] },
  { id: 's-14', thai: 'แต่ฉันชอบกินเผ็ด', rom: 'dtàae chǎn chôrp gin phèt', words: ['แต่', 'ฉัน', 'ชอบ', 'กิน', 'เผ็ด'], en: ['But I like spicy food.', 'But I like eating spicy food.', 'But I like to eat spicy food.'], key: [['but'], ['i'], ['like'], ['spicy', 'hot']] },
  { id: 's-15', thai: 'มานี่', rom: 'maa nîi', words: ['มา', 'นี่'], en: ['Come here.'], key: [['come here']] },
  { id: 's-16', thai: 'ขอบคุณมากครับ', rom: 'khàawp-khun mâak khráp', words: ['ขอบคุณ', 'มาก', 'ครับ'], en: ['Thank you very much.', 'Thanks a lot.', 'Thank you so much.'], key: [['thank', 'thanks'], ['very much', 'a lot', 'so much', 'much']] },
  { id: 's-17', thai: 'ไม่เป็นไรครับ', rom: 'mâi bpen rai khráp', words: ['ไม่เป็นไร', 'ครับ'], en: ["You're welcome.", 'No problem.', 'Never mind.', 'No worries.'], key: [['welcome', 'no problem', 'never mind', 'no worries', 'okay', 'ok', 'all right', 'alright']] },
  { id: 's-18', thai: 'คุณชอบดื่มอะไร', rom: 'khun chôrp dùum à-rai', words: ['คุณ', 'ชอบ', 'ดื่ม', 'อะไร'], en: ['What do you like to drink?', 'What do you like drinking?'], key: [['what'], ['like'], ['drink', 'drinking']] },
  { id: 's-19', thai: 'ฉันชอบดื่มชา', rom: 'chǎn chôrp dùum chaa', words: ['ฉัน', 'ชอบ', 'ดื่ม', 'ชา'], en: ['I like to drink tea.', 'I like drinking tea.', 'I like tea.'], key: [['i'], ['like'], ['tea']], thAlt: ['ฉันชอบชา'] },
  { id: 's-20', thai: 'คุณไปซูเปอร์มาร์เก็ตไหม', rom: 'khun bpai suu-bpəə-maa-gèt mǎi', words: ['คุณ', 'ไป', 'ซูเปอร์มาร์เก็ต', 'ไหม'], en: ['Are you going to the supermarket?', 'Will you go to the supermarket?', 'Do you go to the supermarket?'], key: [['you'], ['go', 'going'], ['supermarket']], avoid: ['which', 'where'], thAlt: ['คุณจะไปซูเปอร์มาร์เก็ตไหม'] },
  { id: 's-21', thai: 'ฉันยังไม่ได้ไป', rom: 'chǎn yang mâi dâai bpai', words: ['ฉัน', 'ยัง', 'ไม่ได้', 'ไป'], en: ["I haven't gone yet.", "I haven't been yet.", "I didn't go yet.", 'Not yet.'], key: [['not'], ['yet']] },
  { id: 's-22', thai: 'คุณเคยไปแคนาดาไหม', rom: 'khun kəəi bpai khae-naa-daa mǎi', words: ['คุณ', 'เคย', 'ไป', 'แคนาดา', 'ไหม'], en: ['Have you ever been to Canada?', 'Have you been to Canada?'], key: [['you'], ['been', 'gone', 'go', 'went'], ['canada']], avoid: ['which', 'where'] },
  { id: 's-23', thai: 'เขาไม่ชอบกาแฟ', rom: 'khǎo mâi chôrp gaa-fae', words: ['เขา', 'ไม่', 'ชอบ', 'กาแฟ'], en: ["He doesn't like coffee.", "She doesn't like coffee.", "They don't like coffee."], key: [['he', 'she', 'they'], ['not'], ['like'], ['coffee']] },
  { id: 's-24', thai: 'เขาชอบกาแฟไหม', rom: 'khǎo chôrp gaa-fae mǎi', words: ['เขา', 'ชอบ', 'กาแฟ', 'ไหม'], en: ['Does he like coffee?', 'Does she like coffee?', 'Do they like coffee?'], key: [['does', 'do'], ['he', 'she', 'they'], ['like'], ['coffee']], avoid: ['which', 'where'] },
  // From a video lesson on everyday verbs.
  { id: 's-25', thai: 'ไปตลาด', rom: 'bpai dtà-làat', words: ['ไป', 'ตลาด'], en: ['Go to the market.', 'Going to the market.', 'I am going to the market.'], key: [['market'], ['go', 'going', 'went']] },
  { id: 's-26', thai: 'ไปทำงาน', rom: 'bpai tham-ngaan', words: ['ไป', 'ทำงาน'], en: ['Go to work.', 'Going to work.', 'I am going to work.'], key: [['work'], ['go', 'going', 'went']] },
  { id: 's-27', thai: 'อยู่บ้าน', rom: 'yùu bâan', words: ['อยู่', 'บ้าน'], en: ['Stay home.', 'Stay at home.', 'I am at home.', 'I am staying home.'], key: [['home', 'house'], ['stay', 'staying', 'at']] },
  { id: 's-28', thai: 'มาบ้านเพื่อน', rom: 'maa bâan phʉ̂an', words: ['มา', 'บ้าน', 'เพื่อน'], en: ["Come to a friend's house.", "Come to my friend's house.", "Came to a friend's house."], key: [['friend'], ['house', 'home', 'place'], ['come', 'came', 'coming']] },
  { id: 's-29', thai: 'เพื่อนมาที่บ้าน', rom: 'phʉ̂an maa thîi bâan', words: ['เพื่อน', 'มา', 'ที่', 'บ้าน'], en: ['My friend came to my house.', 'A friend came to my house.', 'My friend came to the house.', 'A friend is coming to the house.'], key: [['friend'], ['came', 'come', 'coming'], ['house', 'home', 'place']] },
  { id: 's-30', thai: 'วันนี้นอนดึก', rom: 'wan-níi norn dʉ̀k', words: ['วันนี้', 'นอน', 'ดึก'], en: ['I will sleep late today.', 'I will go to bed late today.', 'I am going to bed late today.'], key: [['today', 'tonight'], ['sleep', 'bed'], ['late']], thAlt: ['ฉันวันนี้นอนดึก'] },
  { id: 's-31', thai: 'เมื่อคืนนอนดึก', rom: 'mʉ̂a-khʉʉn norn dʉ̀k', words: ['เมื่อคืน', 'นอน', 'ดึก'], en: ['I went to bed late last night.', 'I slept late last night.', 'Last night I went to bed late.'], key: [['last night'], ['sleep', 'slept', 'bed'], ['late']], thAlt: ['ฉันเมื่อคืนนอนดึก'] },
  { id: 's-32', thai: 'ตื่นเช้าทุกวัน', rom: 'dtʉ̀ʉn cháao thúk wan', words: ['ตื่น', 'เช้า', 'ทุก', 'วัน'], en: ['I wake up early every day.', 'I get up early every day.', 'Wake up early every day.'], key: [['wake', 'get up', 'woke'], ['early', 'morning'], ['every day', 'everyday', 'each day', 'daily']], thAlt: ['ฉันตื่นเช้าทุกวัน'] },
  { id: 's-33', thai: 'ฉันตื่นเช้าไปทำงาน', rom: 'chǎn dtʉ̀ʉn cháao bpai tham-ngaan', words: ['ฉัน', 'ตื่น', 'เช้า', 'ไป', 'ทำงาน'], en: ['I wake up early to go to work.', 'I get up early to go to work.', 'I wake up early and go to work.'], key: [['i'], ['wake', 'get up', 'woke'], ['early', 'morning'], ['work']] },
  { id: 's-34', thai: 'วันนี้ไม่ทำงาน', rom: 'wan-níi mâi tham-ngaan', words: ['วันนี้', 'ไม่', 'ทำงาน'], en: ['I am not working today.', "I don't work today.", 'Not working today.', 'I have no work today.'], key: [['today'], ['not', 'no', 'off'], ['work', 'working']], thAlt: ['ฉันวันนี้ไม่ทำงาน'] },
  { id: 's-35', thai: 'พูดไทยนิดหน่อย', rom: 'phûut thai nít-nàwy', words: ['พูด', 'ไทย', 'นิดหน่อย'], en: ['I speak a little Thai.', 'I can speak a little Thai.', 'Speak a little Thai.'], key: [['speak', 'talk'], ['a little', 'a bit', 'little'], ['thai']], thAlt: ['ฉันพูดไทยนิดหน่อย'] },
  { id: 's-36', thai: 'อยากพูดไทย', rom: 'yàak phûut thai', words: ['อยาก', 'พูด', 'ไทย'], en: ['I want to speak Thai.', 'I would like to speak Thai.', 'Want to speak Thai.'], key: [['want', 'would like'], ['speak', 'talk'], ['thai']], thAlt: ['ฉันอยากพูดไทย'] },
  { id: 's-37', thai: 'พูดมาก', rom: 'phûut mâak', words: ['พูด', 'มาก'], en: ['Talk a lot.', 'You talk a lot.', 'He talks a lot.', 'Talks too much.'], key: [['talk', 'speak', 'talks', 'speaks', 'talking'], ['a lot', 'much', 'lot']] },
  { id: 's-38', thai: 'พูดน้อย', rom: 'phûut nóoi', words: ['พูด', 'น้อย'], en: ["Doesn't talk much.", "Don't talk much.", 'Talks little.', 'Quiet.'], key: [['talk', 'speak', 'talks', 'speaks'], ['not', 'little', 'less']] },
  { id: 's-39', thai: 'โทรหาฉัน', rom: 'thoo hǎa chǎn', words: ['โทร', 'หา', 'ฉัน'], en: ['Call me.', 'Phone me.', 'Give me a call.'], key: [['call', 'phone', 'ring'], ['me']] },
  { id: 's-40', thai: 'ฉันซื้อกาแฟทุกเช้า', rom: 'chǎn sʉ́ʉ gaa-fae thúk cháao', words: ['ฉัน', 'ซื้อ', 'กาแฟ', 'ทุก', 'เช้า'], en: ['I buy coffee every morning.', 'I buy a coffee every morning.', 'Every morning I buy coffee.'], key: [['i'], ['buy', 'get'], ['coffee'], ['every morning', 'each morning', 'mornings']] },
  { id: 's-41', thai: 'เมื่อคืนดูหนัง', rom: 'mʉ̂a-khʉʉn duu nǎng', words: ['เมื่อคืน', 'ดู', 'หนัง'], en: ['I watched a movie last night.', 'I watched a film last night.', 'Last night I watched a movie.'], key: [['last night'], ['watch', 'watched', 'saw', 'see'], ['movie', 'film']], thAlt: ['ฉันเมื่อคืนดูหนัง'] },
  { id: 's-42', thai: 'ทำอะไร', rom: 'tham à-rai', words: ['ทำ', 'อะไร'], en: ['What are you doing?', 'What are you up to?', 'What is he doing?'], key: [['what'], ['doing', 'do', 'does', 'up to']], thAlt: ['คุณทำอะไร'] },
  { id: 's-43', thai: 'ชอบอ่านหนังสือทุกวัน', rom: 'chôrp àan nǎng-sʉ̌ʉ thúk wan', words: ['ชอบ', 'อ่าน', 'หนังสือ', 'ทุก', 'วัน'], en: ['I like to read every day.', 'I like reading every day.', 'I like to read books every day.'], key: [['like', 'enjoy'], ['read', 'reading'], ['every day', 'everyday', 'each day', 'daily']], thAlt: ['ฉันชอบอ่านหนังสือทุกวัน'] },
  { id: 's-44', thai: 'เขียนภาษาไทยไม่เป็น', rom: 'khǐan phaa-sǎa thai mâi bpen', words: ['เขียน', 'ภาษา', 'ไทย', 'ไม่เป็น'], en: ["I don't know how to write Thai.", "I can't write Thai.", 'I cannot write Thai.'], key: [['not', 'cannot', 'can not'], ['write', 'writing'], ['thai']], thAlt: ['ฉันเขียนภาษาไทยไม่เป็น'] },
  { id: 's-45', thai: 'เขียนภาษาไทยนิดหน่อย', rom: 'khǐan phaa-sǎa thai nít-nàwy', words: ['เขียน', 'ภาษา', 'ไทย', 'นิดหน่อย'], en: ['I can write a little bit of Thai.', 'I can write a little Thai.', 'I write a little Thai.'], key: [['write', 'writing'], ['a little', 'a bit', 'little'], ['thai']], thAlt: ['ฉันเขียนภาษาไทยนิดหน่อย'] },
];
